### ISSUE TITLE
입력창과 뷰어의 스크롤 싱크

### ISSUE THREAD

**Issue by KorJeongHyeonLee** [exitsoft/Clev-WEB#16]
입력창과 뷰어에 들어가는 내용의 높이에 차이가 있어 스크롤이 맞지 않는 문제
-> 최소한 입력할 때에는 자동으로 싱크가 맞게 하는 것이 맞다고 생각

**Comment by nayunhwan** [comment]
일단 Preview와 Editor scroll를 각기 다르게 움직이는 것으로 변경
